version: '3.8'

services:
  # FastAPI приложение
  app:
    build: .
    container_name: rit-utils-app
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./src/utils/doctor_form:/app/src/utils/doctor_form
      - ./src/utils/gen_cert:/app/src/utils/gen_cert
      - ./src/utils/send_email:/app/src/utils/send_email
    networks:
      - rit-utils-network
    depends_on:
      - nginx

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: rit-utils-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - rit-utils-network
    depends_on:
      - app

networks:
  rit-utils-network:
    driver: bridge

volumes:
  nginx_logs:
